### ISSUE TITLE
Plugin can be installed if php-cli is not available?

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-PdfText#9]
This [forum post](https://forum.omeka.org/t/re-pdf-text-plugin-does-not-appear-to-extract-fulltext/11632) suggests that users can install the plugin if php-cli is not available. Maybe [the check](https://github.com/omeka/plugin-PdfText/blob/master/PdfTextPlugin.php#L44-L47) during installation is faulty.

**Comment by DBinaghi** [comment]
Hi.
Confirmed: my provider is not enabling access to php-cli, but the plugin gets installed nonetheless, so the check is missing something (no error message is shown, during plugin installation).
I suggest also to check whether the pdftotext function is available, as an extra check.
Hope this helps.

**Comment by jimsafley** [comment]
The plugin does check whether the pdftotext utility is available using `hash pdftotext 2>&- || echo 1`. It calls this using PHP's `shell_exec()`, which, now that I look at it, returns `null` when php-cli isn't available. This accounts for the plugin being able to be installed when it shouldn't. I'm sure there's a better way to make these checks.

**Comment by jimsafley** [comment]
@DBinaghi A point of clarification: the plugin does not, in fact, check whether php-cli is available; it uses `shell_exec()` which your server may have disabled. Check with your server admin about enabling PHP's program execution functions. Sorry for the confusion. PHP-CLI has nothing to do with this issue.

**Comment by DBinaghi** [comment]
> @DBinaghi A point of clarification: the plugin does not, in fact, check whether php-cli is available;

Yes, correct. So, to solve the reported issue, an improved test for the function should be used. But if there was a chance to make the plugin independent  from php-cli, or at least to offer it as an option, it would be great.

**Comment by jimsafley** [comment]
The plugin _is_ independent of php-cli. Your server administrator just needs to enable PHP'S program execution functions. If that's impossible there's no PHP only solution.

**Comment by zerocrates** [comment]
I think we can chalk this one up to some confusion: the upshot being that this plugin doesn't check for the CLI because it doesn't _use_ the CLI (but servers that don't have the CLI may be often the same ones that disable PHP's execution functions).

There may be a different issue currently with how graceful the check is on modern systems though, since PHP 8 just undefines disabled functions.
